#!/bin/bash
check ()
{
cd /opt/systemcheck/
diff $1 $2 > /dev/null
if [ $? == 0 ]
then
echo "No changes in $3." >> green
else
diff  $1 $2 | awk '/>/ {print$0 " <--- '$3' Missing , please check"}' >> red
fi
}
kern()
{
cd /opt/systemcheck/
diff $1 $2 > /dev/null
if [ $? == 0 ]
then
echo "No changes in kernel" >> green
else
echo "Changes in kernel detected...!!" >> red
echo "$(cat bk) <--Old kernel" >> red
echo "$(cat ak) <--New kernel" >> red
fi
}
host()
{
cd /opt/systemcheck/
diff $1 $2 > /dev/null
if [ $? == 0 ]
then
echo "No changes in server hostname" >> green
else
echo "Changes in hostname  detected...!!" >> red
echo "$(cat bh) <--Old hostname" >> red
echo "$(cat ah) <--New hostname" >> red
fi
}
release()
{
cd /opt/systemcheck/
diff $1 $2 > /dev/null
if [ $? == 0 ]
then
echo "No changes in OS Release." >> green
else
echo "Changes in OS Release detected...!!" >> red
echo "$(cat brl) <--Old release version" >> red
echo "$(cat arl) <--New release version" >> red
fi
}
analyze()
{
cd /opt/systemcheck/
test -f after
if [ $? != 0 ]
then
/root/systemcheck collect after
fi

>red
>green
check "before" "after" "Filesystem"
check "brt" "art" "Route"
kern "bk" "ak"
host "bh" "ah"
release "brl" "arl"
}

collect()
{
test -d /opt/systemcheck || mkdir -p /opt/systemcheck
cd /opt/systemcheck/
if [ $1 == "before" ]
then
df -h > before
netstat -nr > brt
uname -r > bk
hostname > bh
cat /etc/redhat-release > brl
fi
if [ $1 == "after" ]
then
df -h > after
netstat -nr > art
uname -r > ak
hostname > ah
cat /etc/redhat-release > arl
fi
}

report()
{
cd /opt/systemcheck/
echo -en "\033[32m"
cat green
echo -en "\033[0m"
echo -en "\033[33m"
test -f red && cat red || echo "No problems detected"
echo -en "\033[0m"
}
clean()
{
cd /opt/systemcheck/
rm -f arl brl bh ah before after brt art  ak bk red green > /dev/null
echo "All the files cleaned"
}
help()
{
echo "Usage: systemcheck [options] ...."
echo
echo -e  "\t1.systemcheck collect before --> Collect the system data before reboot"
echo
echo -e "\t2.systemcheck collect after --> Collect the system data after reboot"
echo
echo -e "\t3.systemcheck analyze --> to analyze the collected data"
echo
echo -e "\t4.systemcheck report --> get the report of analyzed data."
echo
echo -e "\t5.systemcheck [version|v|V] --> to check the version"
echo
echo -e "\t6.systemcheck help --> to print this help menu"
}
ver()
{
echo "systemcheck  : a program to check the system changes after a reboot"
echo
echo "Version      : 1.0"
echo "Release Date : 30-Sept-2015"
}
back()
{
cd /opt/systemcheck/
test -f bh
if [ $? == 0 ]
then
HM=/opt/systemcheck
test -d backup || mkdir backup
cd backup
FILE=backup_$(hostname)_$(date +%d-%m-%Y)
touch $FILE
echo "--------------------->`date`<---------------------">>$FILE
echo "Hostname" >>$FILE
cat $HM/bh >> $FILE
echo "=====================" >> $FILE
echo "Kernel" >>$FILE
cat $HM/bk >>$FILE
echo "=====================" >> $FILE
echo "Release version">>$FILE
cat $HM/brl >>$FILE
echo "=====================" >> $FILE
echo "Fie system" >>$FILE
cat $HM/before >>$FILE
echo "=====================" >> $FILE
echo "Routing table" >>$FILE
cat $HM/brt >> $FILE
echo "------------------------------------------------------------------------------------">>$FILE
echo "Config Backup has been taken..."
else
echo "No files to take backup , run 'systemcheck before' and try again"
exit 3
fi
}

case "$1" in
        collect)
        collect $2
        ;;
        analyze)
        analyze
        ;;
        report)
        report
        ;;
        backup)
        back
        ;;
        clean)
        clean
        ;;
        v|V|version)
        ver
        ;;
        help)
        help
        exit 0
        ;;
        *)
        help
        exit 1
        ;;
        esac
