#!/bin/bash
LOG=~/lnxhard.log
grep HISTTIMEFORMAT /etc/profile >/dev/null 2>&1
if [ $? != 0 ]
then
echo "export HISTTIMEFORMAT=\"%d/%m/%y %T \"" >> /etc/profile
echo "`date +%D"-"%T`:kernel security enabled." >>$LOG
fi
